# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4a35996104a935e8b355bf6aed21e4dbf2f03a6cc3f4614d76ab9c8fc69513380f7c2114daf5f87177bd92c44a0116acea262a32a843a1a0d389bb63bdc2094

test:
  secret_key_base: dc9626057f44c289410c0648f0cd9caabcce10110fe802ace8cc41fbe9b00397d42b1341bb2259365eaab87d4283f0010ca59f50c7e19d10d034a676c384955e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
